const privacyPolicyContent = {
  applicability: [
    "This Privacy Policy is for HelloWorld Technologies India Pvt. Ltd. (HelloWorld) and governs the privacy of its users who share their Information on HelloWorld’s Website (“Website”) or HelloWorld’s Mobile Application (“Mobile App”).",
    "HelloWorld respects the privacy of it's users and is committed to protect it in all respects. With a view to offer most enriching and holistic internet experience to its users, HelloWorld offers a vast repository of Online Sites and variety of community services. The information about the user as collected by HelloWorld is: (a) information supplied by users and (b) information automatically tracked while navigation.",
    "The policy sets out the different areas where user privacy is concerned and outlines the obligations & requirements of the users and the owners. Furthermore the way the Website and the Mobile App processes, stores and protects user data and Information will also be detailed within this policy.",
    "Information herein includes information shared by the user, including, (i) personal information ( details pertaining to user’s name, age, marital status, nationality, state of residence, city of residence, email address, date of birth, gender, contact number/mobile number, recent photograph); (ii) e-KYC through Unique Identification Authority of India (“UIDAI”); (iii) other Know Your Customer (KYC) documents like address proof, identity proof; (iv) bank account details, (v) employment details obtained from social network sites, (vi) such other officially valid documents/details (OVDs)) which are shared/ uploaded by the user through usage of HelloWorld’s Website and Mobile App and through which HelloWorld may become privy to such information.",
    "Such information will not be considered as sensitive if it is freely available and accessible in the public domain or is furnished under the Right to Information Act, 2005 or any other law for the time being in force.",
  ],
  websiteAndApp: [
    "The owners of the Website and Mobile App take a proactive approach to user privacy and ensure that necessary steps are taken to protect the privacy of the Information shared by its users.",
  ],
  consent: [
    "The user expressly consents uploading his/ her Information, as may be necessary to enable HelloWorld to provide required services.",
    "HelloWorld (its affiliates and business partners) may contact the user, either through phone or email, to (i) make follow up calls in relation to the services provided by HelloWorld through its Website; (ii) for imparting product knowledge; (iii) offering promotional offers running on the Website and Mobile App, etc.",
    "By visiting, accessing or availing any services available on the Website or Mobile App, the user explicitly consents to, without limitation or qualification, to the collection, storage, processing disclosure, use and transfer of his/her Personal Information provided by him/her in the manner as described in this Privacy Policy",
  ],
  usage: [
    "HelloWorld will be sharing the user’s Information with their affiliates and business partners at its own discretion. HelloWorld will primarily share the Information for the following reasons: a) analyse usage of the Website and to improve the Service including but not limited to data driven research to improve user experience, create personalized retention programs, etc. b) send the User any offers, and communications relevant to their use of the Service;X c) Carry out market research, project planning, troubleshooting issues, detecting and protecting against error, fraud or other criminal activity; d) bind third-party contractors that provide services to HelloWorld and are bound by these same privacy restrictions; e) to conduct surveys to detect frauds; f) Comply with all applicable laws and regulations;",
    "HelloWorld may also use third party service providers to provide services to the User, such as (a) sending e-mail messages on HelloWorld behalf; or (b) hosting and operating a particular feature or functionality of the Service. Our contracts with these third parties usually prohibit the third party service providers from using any Information for purposes unrelated to the product or service they're providing and require such third parties to maintain the confidentiality of the personal information provide to them.",
    "HelloWorld website may include links to other websites. Such sites are governed by their respective privacy policies, which are beyond our control. Once a user leave our servers, use of any information that he/she so provides is governed by the privacy policy of the operator of the site the user is visiting. That policy may differ from HelloWorld’s. If the user cannot find the privacy policy of any of these sites via a link from the site’s homepage, he/she should contact the site directly for more information.",
  ],
  sharing: [
    "HelloWorld may disclose or transfer any of the user’s Information to any group entity, contractor, service provider, government agency within or outside his/her jurisdiction as may be deemed to be necessary or appropriate including: (a) under applicable law; (b) to comply with legal process; (c) to Auditors; (d) to respond to requests from public and government authorities including public and government authorities outside the user’s country of residence; (f) to enforce HelloWorld’s Terms of Use; (g) to protect HelloWorld’s operations or those of any of our affiliates; (h) to protect HelloWorld’s rights, privacy, safety or property, and/or that of HelloWorld’s affiliates, the user’s or others; and (i) to allow HelloWorld to pursue available remedies or limit the damages that HelloWorld may sustain.",
    "In addition, HelloWorld may disclose or transfer the user’s Information with other corporate entities and affiliates within or outside his/her jurisdiction to: a) Help detect and prevent identity theft, fraud and other potentially illegal acts; b) Correlate related or multiple accounts to prevent abuse of HelloWorld’s services available on the Site; and c) To facilitate joint or co-branded services that the user request for where such services are provided by more than one corporate entity. d) To directly or indirectly report your payment behaviour to Credit Bureaus",
    "HelloWorld may disclose or transfer the user’s Information within or outside his/her jurisdiction to HelloWorld’s third party providers who provide goods/services such as contact information verification, payment processing, order fulfilment, customer service, website hosting, data analysis, infrastructure provision, IT services, auditing services and other similar services to enable them to provide the relevant services.",
    "The user acknowledges that some entities and /or countries where we may transfer his/her Personal Information may not comply with data protection policies which are as stringent as the laws of his/her own country or the policies followed by HelloWorld. The user acknowledges that it is adequate that when HelloWorld transfers his/her Personal Information to any other entity within or outside his/her country of residence, HelloWorld will place contractual obligations on the transferee which will oblige the transferee to adhere to the provisions of this Privacy Policy.",
    "Posting certain requirements on the Site for certain properties, whether for sale or rent, may require the user to provide HelloWorld with Personal Information such as his/her valid ID proof and proof of employment, prior to posting such requirements. The user hereby acknowledges and permit HelloWorld (directly or through its contractors) to contact him/her to at the contact number as provided by him/her, for intimating him/her on events, potential buyers, tenants or properties that other Site users might be interested in. The user further consent to HelloWorld maintaining in our records his/her contact details that would be used for customer inquiry purposes.",
  ],
  additional: [
    "Single Sign-On: The user can login to HelloWorld’s Website or Mobile App using sign-in services such as Facebook, Google or Linkedin. These services will authenticate the user’s identity and provide the user, the option to share certain Information with HelloWorld, such as, their sign-in information, name and email address to link between the sites. Social networking media services like Facebook and Twitter give you the option to post information about your activities on this Website to your profile page to share with others within your network.",
    "Communication, engagement and actions taken through external social media platforms that this website and its owners participate on are custom to the terms and conditions as well as the privacy policies held with each social media platform respectively.",
    "Users are advised to use social media platforms wisely and communicate / engage upon them with due care and caution in regard to their own privacy and personal details. This website may ask for personal or sensitive information through social media platforms.",
    "This website may use social sharing buttons which help share web content directly from web pages to the social media platform in question. Users are advised before using such social sharing buttons that they do so at their own discretion and note that the social media platform may track and save your request to share a web page respectively through your social media platform account.",
  ],
  data: [
    "HelloWorld takes appropriate security procedures, which includes internal reviews of HelloWorld data collection, storage and processing practices and security measures, including appropriate encryption and physical security measures to guard against unauthorized access to systems where HelloWorld stores Information provided by the user.",
    "The information HelloWorld obtains from or about the user are processed and stored in cloud anywhere in World. HelloWorld complies with generally accepted industry standard regulations regarding collection, use, and retention of data. By using the Services, the user consents to the collection, transfer, use, storage and disclosure of his/her Information as described in this Privacy Policy and under applicable laws.",
  ],
  confidentiality: [
    "The user is responsible for maintaining the security of his/her Login ID and Password, and may not provide these credentials to any third party. If the users believe that they have been stolen or been made known to others, the user must contact us immediately at legal@thehelloworld.com. HelloWorld is not responsible if someone else accesses the users account through registration information they have obtained from the user or through a violation by the user of this Policy of Use.",
  ],
  cookies: [
    "To improve the responsiveness of the sites for the users, HelloWorld may use 'cookies', or similar electronic tools to collect information to assign each visitor a unique, random number as a User Identification (User ID) to understand the user's individual interests using the Identified Computer. Unless the user voluntarily identify himself/herself (through registration, for example), HelloWorld will have no way of knowing who the user is, even if HelloWorld assign a cookie to the user’s computer. The only Personal Information a cookie can contain is information the user supply. A cookie cannot read data off the hard drive. HelloWorld’s advertisers may also assign their own cookies to the user’s browser (if the user click on their ads), a process that HelloWorld do not control.",
    "HelloWorld web servers automatically collect limited information about the user’s computer's connection to the Internet, including the IP address, when he/she visit the Website. (The IP address is a number that lets computers attached to the Internet know where to send data -- such as the web pages the user view.) The IP address does not identify a user personally. HelloWorld uses this information to deliver its web pages to the user upon request, to tailor the Website to the interests of its users, to measure traffic within the Website and let advertisers know the geographic locations from where the visitors come.",
    "When a user uses one of the location-enabled services (for example, when he/she access Services from a mobile device), HelloWorld may collect and process information about the mobile device’s GPS location (including the latitude, longitude or altitude of your mobile device) and the time the location information is recorded to customize the Services with location-based information and features (for example, to inform you about restaurants in your area or applicable promotions). Some of these services require personal data for the feature to work and HelloWorld may associate location data with the users device ID and other information. If a user wishes to use the particular feature, he/she will be asked to consent to the users data being used for this purpose. The user can withdraw his/her consent at any time by disabling the GPS or other location-tracking functions on the device, provided the device allows to do this. See the device manufacturer’s instructions for further details.",
  ],
  communication: [
    "Users contacting this website and/or its owners do so at their own discretion and provide any personal details including but not limited to name, age, gender, email id, contact details, etc., requested by the owner of this Website. Information is kept private and stored securely until a time it is no longer required or has no use. Every effort has been made to ensure a safe and secure form to email submission process but advise users using such form to email processes that they do so at their own risk.",
  ],
  sponsored: [
    "This website may contain sponsored links and adverts. These will typically be served through our advertising partners, to whom may have detailed privacy policies relating directly to the adverts they serve.",
    "Clicking on any such adverts will send you to the advertisers website through a referral program which may use cookies and will track the number of referrals sent from this website. This may include the use of cookies which may in turn be saved on your computers hard drive. Users should therefore note they click on sponsored external links at their own risk and this website and its owners cannot be held liable for any damages or implications caused by visiting any external links mentioned.",
    "Some of the advertisements seen on the Website are selected and delivered by third parties, such as advertisement networks, advertising agencies, advertisers, and audience segment providers. These third parties may collect Personal Information from the user during the course of his/her online activities, either on the Site or on other websites, through cookies, web beacons, and other technologies in an effort to understand his/her interests and deliver to him/her advertisements that are tailored to his/her interests.",
    "Please remember that the HelloWorld does not have access to, or control over, the information these third parties may collect. The information practices of these third parties are not covered by this Privacy Policy. HelloWorld would not be liable for any loss or damage caused to the user as a result of such third parties collecting such Personal Information, or any other types of information from him/her.",
    "During the user’s interactions with HelloWorld, it may happen that We provide/include links and hyperlinks of third party websites. It may also happen that the user include links and hyperlinks of third party websites. The listing of such third party external sites (by the user or by HelloWorld) does not imply endorsement of such site by HelloWorld. Such third party sites are governed by their own terms and conditions and when the user access such third party sites, he/she will be governed by the terms of such third party sites. HelloWorld do not make any representations regarding the availability and performance of any of the external sites. HelloWorld is not responsible for the content, terms of use, privacy policies and practices of such third party websites.",
  ],
  changes: [
    "It is strongly recommended for you to return to this page periodically to review the most current version of the Policy. HelloWorld reserves the right at any time, at its sole discretion, to change or otherwise modify the Policy without prior notice, and your continued access or use of this Website signifies your acceptance of the updated or modified Policy. However, if we make any material change to the Policy, we will notify you by means of a notice on this Website prior to the change becoming effective.",
    "A material change is a change made by HelloWorld in the following clauses of the privacy policy (i) Privacy Policy use and applicability; (ii) Third Party Usage of Data; (3) Disclosure/ Sharing; (iv) Confidentiality.This Privacy Policy has been last updated on 16/11/2017.",
  ],
} as const;

export default privacyPolicyContent;
