export interface CitySrpSeoMetadata {
  metaDescription: string
  pageDescription: string
}

export const colivingCitywiseSrpSeoMetadata: Record<string, CitySrpSeoMetadata> = {
  ahmedabad: {
    metaDescription:
      'Find the best coliving spaces in Ahmedabad with furnished rooms, Wi-Fi, food, housekeeping, and easy access to colleges, offices, and key city areas. Explore affordable boys PG, girls PG, ladies PG, and gents PG options.',
    pageDescription:
      'Looking for the best coliving in Ahmedabad? HelloWorld offers fully furnished coliving spaces and PG accommodation for students, working professionals, interns, and remote workers. Choose from private rooms, twin sharing, triple sharing, boys PG, girls PG, ladies PG, and gents PG options with amenities such as high-speed Wi-Fi, meals, housekeeping, laundry, CCTV security, power backup, and community spaces.\n\nYou can find PG and coliving spaces in popular Ahmedabad areas including SG Highway, Prahlad Nagar, Navrangpura, Satellite, Vastrapur, Bodakdev, and Thaltej. These locations are popular because they are close to offices, colleges, shopping hubs, and well-connected city routes.\n\nWhether you are searching for a boys PG in SG Highway, a girls PG in Navrangpura, a ladies PG in Satellite, or a gents PG in Prahlad Nagar, HelloWorld offers safe, affordable, and fully furnished accommodation with food, Wi-Fi, housekeeping, and security.\n\nHelloWorld properties are located close to major business and education hubs, helping residents reduce travel time and stay connected to work, study, and everyday essentials.\n\nWith flexible rent, zero brokerage, ready-to-move rooms, and premium amenities, HelloWorld makes it easy to find affordable and modern coliving in Ahmedabad.'
  },
  bangalore: {
    metaDescription:
      'Find the best coliving spaces in Bangalore with furnished rooms, Wi-Fi, food, housekeeping, and easy access to IT parks and metro stations. Explore boys PG, girls PG, ladies PG, and gents PG in HSR Layout, Koramangala, Whitefield, Bellandur, Marathahalli, and more.',
    pageDescription:
      'Looking for the best coliving in Bangalore? HelloWorld offers fully furnished coliving spaces and PG accommodation for students, working professionals, couples, and remote workers. Choose from private rooms, twin sharing, triple sharing, boys PG, girls PG, ladies PG, and gents PG options with modern amenities such as high-speed Wi-Fi, meals, housekeeping, laundry, CCTV security, power backup, and community spaces.\n\nYou can find PG and coliving spaces in popular Bangalore areas including HSR Layout, Koramangala, Whitefield, Indiranagar, Marathahalli, Bellandur, Electronic City, BTM Layout, and Sarjapur Road. These areas are popular because they are close to offices, colleges, tech parks, and metro connectivity.\n\nWhether you are searching for a boys PG in HSR Layout, a girls PG in Koramangala, a ladies PG near Whitefield, or a gents PG in Marathahalli, HelloWorld offers safe, affordable, and fully furnished accommodation with food, Wi-Fi, housekeeping, and security.\n\nHelloWorld properties are located close to major employment hubs such as Manyata Tech Park, Embassy Tech Village, RMZ Ecoworld, Bagmane Tech Park, Prestige Tech Park, and the Namma Metro, helping residents reduce travel time and stay close to work.\n\nWith flexible rent, zero brokerage, ready-to-move rooms, and premium amenities, HelloWorld makes it easy to find affordable and modern coliving in Bangalore.'
  },
  coimbatore: {
    metaDescription:
      'Find the best coliving spaces in Coimbatore with furnished rooms, Wi-Fi, food, housekeeping, and easy access to colleges, offices, and major city zones. Explore affordable boys PG, girls PG, ladies PG, and gents PG options.',
    pageDescription:
      'Looking for the best coliving in Coimbatore? HelloWorld offers fully furnished coliving spaces and PG accommodation for students, working professionals, interns, and remote workers. Choose from private rooms, twin sharing, triple sharing, boys PG, girls PG, ladies PG, and gents PG options with amenities such as high-speed Wi-Fi, meals, housekeeping, laundry, CCTV security, power backup, and community spaces.\n\nYou can find PG and coliving spaces in popular Coimbatore areas including Gandhipuram, Peelamedu, Saravanampatti, RS Puram, Singanallur, and Hope College. These locations are preferred because they are close to colleges, business centres, transport links, and daily convenience hubs.\n\nWhether you are searching for a boys PG in Peelamedu, a girls PG in Saravanampatti, a ladies PG near RS Puram, or a gents PG in Gandhipuram, HelloWorld offers safe, affordable, and fully furnished accommodation with food, Wi-Fi, housekeeping, and security.\n\nHelloWorld properties are located close to education hubs, office zones, and key city landmarks, helping residents stay connected and reduce daily commute time.\n\nWith flexible rent, zero brokerage, ready-to-move rooms, and premium amenities, HelloWorld makes it easy to find affordable and modern coliving in Coimbatore.'
  },
  chennai: {
    metaDescription:
      'Find the best coliving spaces in Chennai with furnished rooms, Wi-Fi, food, housekeeping, and easy access to OMR, Guindy, Porur, and metro-connected areas. Explore affordable boys PG, girls PG, ladies PG, and gents PG options.',
    pageDescription:
      'Looking for the best coliving in Chennai? HelloWorld offers fully furnished coliving spaces and PG accommodation for students, working professionals, interns, and remote workers. Choose from private rooms, twin sharing, triple sharing, boys PG, girls PG, ladies PG, and gents PG options with amenities such as high-speed Wi-Fi, meals, housekeeping, laundry, CCTV security, power backup, and community spaces.\n\nYou can find PG and coliving spaces in popular Chennai areas including OMR, Guindy, Porur, Velachery, Sholinganallur, Perungudi, and Thoraipakkam. These locations are preferred because they are close to IT parks, colleges, commercial hubs, and major commute routes.\n\nWhether you are searching for a boys PG in OMR, a girls PG in Velachery, a ladies PG near Guindy, or a gents PG in Sholinganallur, HelloWorld offers safe, affordable, and fully furnished accommodation with food, Wi-Fi, housekeeping, and security.\n\nHelloWorld properties are located close to leading employment centres, helping residents stay near work hubs, reduce travel time, and enjoy convenient city living.\n\nWith flexible rent, zero brokerage, ready-to-move rooms, and premium amenities, HelloWorld makes it easy to find affordable and modern coliving in Chennai.'
  },
  delhi: {
    metaDescription:
      'Find the best coliving spaces in Delhi with furnished rooms, Wi-Fi, food, housekeeping, and easy access to metro stations, offices, and colleges. Explore affordable PG and coliving options in South Delhi, North Campus, Lajpat Nagar, Saket, Hauz Khas, and more.',
    pageDescription:
      'Looking for the best coliving in Delhi? HelloWorld offers fully furnished coliving spaces and PG accommodation for students, working professionals, interns, and remote workers. Choose from private rooms, twin sharing, triple sharing, and shared accommodation with modern amenities such as high-speed Wi-Fi, meals, housekeeping, laundry, CCTV security, power backup, and community spaces.\n\nYou can find PG and coliving spaces in popular Delhi locations including South Delhi, Lajpat Nagar, Saket, Hauz Khas, Mukherjee Nagar, Karol Bagh, and around Delhi University North Campus. These areas are preferred by students and professionals because of their connectivity, cafes, markets, and access to colleges and offices.\n\nHelloWorld properties are located close to major business districts and metro-connected areas such as Connaught Place, Nehru Place, Okhla Industrial Area, and the Delhi Metro, making daily travel easier and faster.\n\nWith zero brokerage, flexible stay options, fully furnished rooms, and premium amenities, HelloWorld makes it easy to find affordable and comfortable coliving in Delhi.'
  },
  goa: {
    metaDescription:
      'Find the best coliving spaces in Goa with furnished rooms, Wi-Fi, food, housekeeping, and easy access to beaches, coworking hubs, and lifestyle neighbourhoods. Explore affordable boys PG, girls PG, ladies PG, and gents PG options.',
    pageDescription:
      'Looking for the best coliving in Goa? HelloWorld offers fully furnished coliving spaces and PG accommodation for students, working professionals, remote workers, and long-stay travellers. Choose from private rooms, twin sharing, triple sharing, boys PG, girls PG, ladies PG, and gents PG options with amenities such as high-speed Wi-Fi, meals, housekeeping, laundry, CCTV security, power backup, and community spaces.\n\nYou can find PG and coliving spaces in popular Goa areas including Panaji, Porvorim, Mapusa, Dona Paula, Vasco, and other well-connected neighbourhoods. These locations are popular because they are close to beaches, cafés, coworking spaces, offices, and everyday essentials.\n\nWhether you are searching for a boys PG in Panaji, a girls PG in Porvorim, a ladies PG near Dona Paula, or a gents PG in Mapusa, HelloWorld offers safe, affordable, and fully furnished accommodation with food, Wi-Fi, housekeeping, and security.\n\nHelloWorld properties are located close to key lifestyle and work hubs, helping residents enjoy flexible living with easy access to both work and leisure.\n\nWith flexible rent, zero brokerage, ready-to-move rooms, and premium amenities, HelloWorld makes it easy to find affordable and modern coliving in Goa.'
  },
  gurugram: {
    metaDescription:
      'Find the best coliving spaces in Gurugram with furnished rooms, Wi-Fi, food, housekeeping, and easy access to Cyber City, Golf Course Road, Udyog Vihar, and metro stations. Explore affordable PG and coliving options for boys, girls, ladies, and gents.',
    pageDescription:
      'Looking for the best coliving in Gurugram? HelloWorld offers fully furnished coliving spaces and PG accommodation for students, working professionals, couples, and remote workers. Choose from private rooms, twin sharing, triple sharing, boys PG, girls PG, ladies PG, and gents PG options with modern amenities such as high-speed Wi-Fi, meals, housekeeping, laundry, CCTV security, power backup, and community spaces.\n\nYou can find PG and coliving spaces in popular Gurugram locations including DLF Cyber City, Golf Course Road, Udyog Vihar, Sector 14, Sector 29, Sector 44, Sohna Road, and MG Road. These areas are ideal for people who want to stay close to offices, metro stations, and commercial hubs.\n\nWhether you are searching for a boys PG in Gurugram, a girls PG near DLF Cyber City, a ladies PG on Golf Course Road, or a gents PG in Udyog Vihar, HelloWorld offers safe, affordable, and fully furnished accommodation.\n\nHelloWorld properties are located close to major employment hubs such as Cyber Hub, One Horizon Center, Global Business Park, and the Delhi Metro, helping residents reduce commute time and stay connected.\n\nWith zero brokerage, flexible stay options, fully furnished rooms, and premium amenities, HelloWorld makes it easy to find affordable and modern coliving in Gurugram.'
  },
  hyderabad: {
    metaDescription:
      'Find the best coliving spaces in Hyderabad with furnished rooms, Wi-Fi, food, housekeeping, and easy access to HITEC City, Gachibowli, offices, and metro routes. Explore affordable boys PG, girls PG, ladies PG, and gents PG options.',
    pageDescription:
      'Looking for the best coliving in Hyderabad? HelloWorld offers fully furnished coliving spaces and PG accommodation for students, working professionals, couples, and remote workers. Choose from private rooms, twin sharing, triple sharing, boys PG, girls PG, ladies PG, and gents PG options with amenities such as high-speed Wi-Fi, meals, housekeeping, laundry, CCTV security, power backup, and community spaces.\n\nYou can find PG and coliving spaces in popular Hyderabad areas including HITEC City, Gachibowli, Madhapur, Kondapur, Kukatpally, Ameerpet, and Financial District. These locations are preferred because they are close to IT parks, offices, colleges, and major commute routes.\n\nWhether you are searching for a boys PG in Madhapur, a girls PG in Gachibowli, a ladies PG near Kondapur, or a gents PG in Kukatpally, HelloWorld offers safe, affordable, and fully furnished accommodation with food, Wi-Fi, housekeeping, and security.\n\nHelloWorld properties are located close to major employment hubs and metro-connected areas, helping residents reduce travel time and stay near work and city essentials.\n\nWith flexible rent, zero brokerage, ready-to-move rooms, and premium amenities, HelloWorld makes it easy to find affordable and modern coliving in Hyderabad.'
  },
  indore: {
    metaDescription:
      'Find the best coliving spaces in Indore with furnished rooms, Wi-Fi, food, housekeeping, and easy access to colleges, offices, and key city neighbourhoods. Explore affordable boys PG, girls PG, ladies PG, and gents PG options.',
    pageDescription:
      'Looking for the best coliving in Indore? HelloWorld offers fully furnished coliving spaces and PG accommodation for students, working professionals, interns, and remote workers. Choose from private rooms, twin sharing, triple sharing, boys PG, girls PG, ladies PG, and gents PG options with amenities such as high-speed Wi-Fi, meals, housekeeping, laundry, CCTV security, power backup, and community spaces.\n\nYou can find PG and coliving spaces in popular Indore areas including Vijay Nagar, Bhawar Kuan, Palasia, Rau, AB Road, and Bengali Square. These locations are popular because they are close to colleges, offices, coaching centres, shopping areas, and major commute routes.\n\nWhether you are searching for a boys PG in Vijay Nagar, a girls PG in Bhawar Kuan, a ladies PG near Palasia, or a gents PG in Rau, HelloWorld offers safe, affordable, and fully furnished accommodation with food, Wi-Fi, housekeeping, and security.\n\nHelloWorld properties are located close to key education and business hubs, helping residents stay connected and reduce daily travel time.\n\nWith flexible rent, zero brokerage, ready-to-move rooms, and premium amenities, HelloWorld makes it easy to find affordable and modern coliving in Indore.'
  },
  jaipur: {
    metaDescription:
      'Find the best coliving spaces in Jaipur with furnished rooms, Wi-Fi, food, housekeeping, and easy access to colleges, offices, and metro stations. Explore affordable PG and coliving options for boys, girls, ladies, and gents.',
    pageDescription:
      'Looking for the best coliving in Jaipur? HelloWorld offers fully furnished coliving spaces and PG accommodation for students, working professionals, interns, and remote workers. Choose from private rooms, twin sharing, triple sharing, boys PG, girls PG, ladies PG, and gents PG options with amenities such as high-speed Wi-Fi, meals, housekeeping, laundry, CCTV security, power backup, and community spaces.\n\nYou can find PG and coliving spaces in popular Jaipur areas including Malviya Nagar, Vaishali Nagar, Mansarovar, Jagatpura, C-Scheme, Tonk Road, and Raja Park. These locations are preferred because they are close to colleges, coaching centres, offices, shopping areas, and metro connectivity.\n\nWhether you are searching for a boys PG in Jaipur, a girls PG in Malviya Nagar, a ladies PG near Jaipur International Airport, or a gents PG in Mansarovar, HelloWorld offers safe, affordable, and fully furnished accommodation with food, Wi-Fi, and security.\n\nHelloWorld properties are located close to major landmarks and institutions such as World Trade Park, Jaipur International Airport, Jaipur National University, MNIT Jaipur, and the Jaipur Metro.\n\nWith flexible rent, zero brokerage, ready-to-move rooms, and premium amenities, HelloWorld makes it easy to find affordable and modern coliving in Jaipur.'
  },
  kolkata: {
    metaDescription:
      'Find the best coliving spaces in Kolkata with furnished rooms, Wi-Fi, food, housekeeping, and easy access to Salt Lake, New Town, offices, and colleges. Explore affordable boys PG, girls PG, ladies PG, and gents PG options.',
    pageDescription:
      'Looking for the best coliving in Kolkata? HelloWorld offers fully furnished coliving spaces and PG accommodation for students, working professionals, interns, and remote workers. Choose from private rooms, twin sharing, triple sharing, boys PG, girls PG, ladies PG, and gents PG options with amenities such as high-speed Wi-Fi, meals, housekeeping, laundry, CCTV security, power backup, and community spaces.\n\nYou can find PG and coliving spaces in popular Kolkata areas including Salt Lake, New Town, Park Street, Ballygunge, Dum Dum, and Sector V. These locations are preferred because they are close to offices, colleges, metro routes, and commercial hubs.\n\nWhether you are searching for a boys PG in Salt Lake, a girls PG in New Town, a ladies PG near Park Street, or a gents PG in Sector V, HelloWorld offers safe, affordable, and fully furnished accommodation with food, Wi-Fi, housekeeping, and security.\n\nHelloWorld properties are located close to key employment and education centres, helping residents reduce commute time and stay connected to everyday essentials.\n\nWith flexible rent, zero brokerage, ready-to-move rooms, and premium amenities, HelloWorld makes it easy to find affordable and modern coliving in Kolkata.'
  },
  mumbai: {
    metaDescription:
      'Find the best coliving spaces in Mumbai with furnished rooms, Wi-Fi, food, housekeeping, and easy access to business districts, colleges, and local train or metro routes. Explore affordable boys PG, girls PG, ladies PG, and gents PG options.',
    pageDescription:
      'Looking for the best coliving in Mumbai? HelloWorld offers fully furnished coliving spaces and PG accommodation for students, working professionals, interns, and remote workers. Choose from private rooms, twin sharing, triple sharing, boys PG, girls PG, ladies PG, and gents PG options with amenities such as high-speed Wi-Fi, meals, housekeeping, laundry, CCTV security, power backup, and community spaces.\n\nYou can find PG and coliving spaces in popular Mumbai areas including Powai, Andheri, Navi Mumbai, Vashi, Ghatkopar, Lower Parel, and Thane. These locations are popular because they are close to offices, colleges, business hubs, and strong public transport connectivity.\n\nWhether you are searching for a boys PG in Powai, a girls PG in Andheri, a ladies PG near Ghatkopar, or a gents PG in Vashi, HelloWorld offers safe, affordable, and fully furnished accommodation with food, Wi-Fi, housekeeping, and security.\n\nHelloWorld properties are located close to major employment hubs and commute corridors, helping residents reduce travel time and stay near work, study, and city essentials.\n\nWith flexible rent, zero brokerage, ready-to-move rooms, and premium amenities, HelloWorld makes it easy to find affordable and modern coliving in Mumbai.'
  },
  noida: {
    metaDescription:
      'Find the best coliving spaces in Noida with furnished rooms, Wi-Fi, food, housekeeping, and easy access to offices, colleges, and metro stations. Explore affordable boys PG, girls PG, ladies PG, and gents PG options across key sectors.',
    pageDescription:
      'Looking for the best coliving in Noida? HelloWorld offers fully furnished coliving spaces and PG accommodation for students, working professionals, interns, and remote workers. Choose from private rooms, twin sharing, triple sharing, boys PG, girls PG, ladies PG, and gents PG options with amenities such as high-speed Wi-Fi, meals, housekeeping, laundry, CCTV security, power backup, and community spaces.\n\nYou can find PG and coliving spaces in popular Noida areas including Sector 18, Sector 62, Sector 137, Sector 15, Sector 76, and other well-connected neighbourhoods. These locations are preferred because they are close to business parks, colleges, metro stations, and daily convenience hubs.\n\nWhether you are searching for a boys PG in Sector 62, a girls PG in Sector 137, a ladies PG near Sector 18, or a gents PG in Sector 15, HelloWorld offers safe, affordable, and fully furnished accommodation with food, Wi-Fi, housekeeping, and security.\n\nHelloWorld properties are located close to key employment centres and metro-connected zones, helping residents stay near work and reduce daily commute time.\n\nWith flexible rent, zero brokerage, ready-to-move rooms, and premium amenities, HelloWorld makes it easy to find affordable and modern coliving in Noida.'
  },
  pune: {
    metaDescription:
      'Find the best coliving spaces in Pune with furnished rooms, Wi-Fi, food, housekeeping, and easy access to Hinjewadi, Kharadi, offices, and colleges. Explore affordable boys PG, girls PG, ladies PG, and gents PG options.',
    pageDescription:
      'Looking for the best coliving in Pune? HelloWorld offers fully furnished coliving spaces and PG accommodation for students, working professionals, couples, and remote workers. Choose from private rooms, twin sharing, triple sharing, boys PG, girls PG, ladies PG, and gents PG options with amenities such as high-speed Wi-Fi, meals, housekeeping, laundry, CCTV security, power backup, and community spaces.\n\nYou can find PG and coliving spaces in popular Pune areas including Hinjewadi, Kharadi, Viman Nagar, Wakad, Baner, Hadapsar, and Magarpatta. These locations are preferred because they are close to IT parks, colleges, offices, and major commute routes.\n\nWhether you are searching for a boys PG in Hinjewadi, a girls PG in Kharadi, a ladies PG near Viman Nagar, or a gents PG in Wakad, HelloWorld offers safe, affordable, and fully furnished accommodation with food, Wi-Fi, housekeeping, and security.\n\nHelloWorld properties are located close to major employment hubs and education zones, helping residents reduce travel time and stay near work and study destinations.\n\nWith flexible rent, zero brokerage, ready-to-move rooms, and premium amenities, HelloWorld makes it easy to find affordable and modern coliving in Pune.'
  },
  visakhapatnam: {
    metaDescription:
      'Find the best coliving spaces in Visakhapatnam with furnished rooms, Wi-Fi, food, housekeeping, and easy access to colleges, offices, and key city neighbourhoods. Explore affordable boys PG, girls PG, ladies PG, and gents PG options.',
    pageDescription:
      'Looking for the best coliving in Visakhapatnam? HelloWorld offers fully furnished coliving spaces and PG accommodation for students, working professionals, interns, and remote workers. Choose from private rooms, twin sharing, triple sharing, boys PG, girls PG, ladies PG, and gents PG options with amenities such as high-speed Wi-Fi, meals, housekeeping, laundry, CCTV security, power backup, and community spaces.\n\nYou can find PG and coliving spaces in popular Visakhapatnam areas including MVP Colony, Madhurawada, Dwaraka Nagar, Gajuwaka, Rushikonda, and Siripuram. These locations are preferred because they are close to colleges, offices, transport links, and important city landmarks.\n\nWhether you are searching for a boys PG in MVP Colony, a girls PG in Madhurawada, a ladies PG near Dwaraka Nagar, or a gents PG in Gajuwaka, HelloWorld offers safe, affordable, and fully furnished accommodation with food, Wi-Fi, housekeeping, and security.\n\nHelloWorld properties are located close to education centres, business hubs, and well-connected neighbourhoods, helping residents stay near daily essentials and reduce travel time.\n\nWith flexible rent, zero brokerage, ready-to-move rooms, and premium amenities, HelloWorld makes it easy to find affordable and modern coliving in Visakhapatnam.'
  }
}

export const hostelCitywiseSrpSeoMetadata: Record<string, CitySrpSeoMetadata> = {
  kota: {
    metaDescription:
      'Find the best hostels in Kota for boys, girls, ladies, and gents near Allen, Resonance, Motion, Vibrant, and other coaching institutes. Explore furnished rooms with food, Wi-Fi, study areas, and security.',
    pageDescription:
      'Looking for the best hostel in Kota for JEE or NEET preparation? HelloWorld offers safe, affordable, and fully furnished hostels and student accommodation for boys, girls, ladies, and gents near the city’s top coaching institutes. Choose from private rooms, twin sharing, triple sharing, AC rooms, non-AC rooms, boys hostel, girls hostel, ladies hostel, and gents hostel options with modern amenities such as nutritious meals, high-speed Wi-Fi, study desks, housekeeping, laundry, CCTV security, wardens, and power backup.\n\nYou can find hostels in popular student areas including Talwandi, Rajeev Gandhi Nagar, Indra Vihar, Mahaveer Nagar, Jawahar Nagar, and Vigyan Nagar. These areas are popular because they are close to coaching centres, libraries, food outlets, and public transport.\n\nWhether you are searching for a boys hostel in Talwandi, a girls hostel in Rajeev Gandhi Nagar, a ladies hostel near Allen Career Institute, or a gents hostel in Indra Vihar, HelloWorld offers verified and fully furnished accommodation with meals, study spaces, and security.\n\nHelloWorld properties are located close to leading coaching institutes such as Allen Career Institute, Resonance, Motion Education, Vibrant Academy, Career Point, and Unacademy Centre, helping students reduce travel time and focus on studies.\n\nWith flexible rent, zero brokerage, ready-to-move rooms, and modern amenities, HelloWorld makes it easy to find the right student hostel in Kota'
  }
}

export function getCitywiseSrpSeoMetadata (
  city: string,
  livingType: 'coliving' | 'hostels',
  slugGender?: 'male only' | 'female only'
): CitySrpSeoMetadata | undefined {
  if (slugGender) return undefined

  if (livingType === 'hostels') {
    return hostelCitywiseSrpSeoMetadata[city.toLowerCase()]
  }

  return colivingCitywiseSrpSeoMetadata[city.toLowerCase()]
}
