export const typeScale = [
  {
    name: "Display 2xl",
    className: "text-display-2xl",
    size: "72px / 4.5rem",
    lineHeight: "90px / 5.625rem",
    letterSpacing: "-2%",
  },
  {
    name: "Display xl",
    className: "text-display-xl",
    size: "60px / 3.75rem",
    lineHeight: "72px / 4.5rem",
    letterSpacing: "-2%",
  },
  {
    name: "Display lg",
    className: "text-display-lg",
    size: "48px / 3rem",
    lineHeight: "60px / 3.75rem",
    letterSpacing: "-2%",
  },
  {
    name: "Display md",
    className: "text-display-md",
    size: "36px / 2.25rem",
    lineHeight: "44px / 2.75rem",
    letterSpacing: "-2%",
  },
  {
    name: "Display sm",
    className: "text-display-sm",
    size: "30px / 1.875rem",
    lineHeight: "38px / 2.375rem",
    letterSpacing: "0",
  },
  {
    name: "Display xs",
    className: "text-display-xs",
    size: "24px / 1.5rem",
    lineHeight: "32px / 2rem",
    letterSpacing: "0",
  },
  {
    name: "Text xl",
    className: "text-xl",
    size: "20px / 1.25rem",
    lineHeight: "30px / 1.875rem",
    letterSpacing: "0",
  },
  {
    name: "Text lg",
    className: "text-lg",
    size: "18px / 1.125rem",
    lineHeight: "28px / 1.75rem",
    letterSpacing: "0",
  },
  {
    name: "Text md",
    className: "text-base",
    size: "16px / 1rem",
    lineHeight: "24px / 1.5rem",
    letterSpacing: "0",
  },
  {
    name: "Text sm",
    className: "text-sm",
    size: "14px / 0.875rem",
    lineHeight: "20px / 1.25rem",
    letterSpacing: "0",
  },
  {
    name: "Text xs",
    className: "text-xs",
    size: "12px / 0.75rem",
    lineHeight: "18px / 1.125rem",
    letterSpacing: "0",
  },
] as const;

export const fontFamilies = [
  {
    name: "Satoshi",
    variable: "--font-satoshi",
    className: "font-satoshi",
    sample: "The quick brown fox jumps over the lazy dog.",
    alphabet: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z",
    numerals: "0 1 2 3 4 5 6 7 8 9",
  },
  {
    name: "Playfair Display",
    variable: "--font-playfair",
    className: "font-playfair",
    sample: "The quick brown fox jumps over the lazy dog.",
    alphabet: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z",
    numerals: "0 1 2 3 4 5 6 7 8 9",
  },
  {
    name: "Caveat",
    variable: "--font-caveat",
    className: "font-caveat",
    sample: "The quick brown fox jumps over the lazy dog.",
    alphabet: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z",
    numerals: "0 1 2 3 4 5 6 7 8 9",
  },
] as const;
